# Generated by Django 5.1.4 on 2024-12-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='auth',
            field=models.CharField(default='f2f7ceb401fd062499c2609869fdd8f968369131626529661af130b4f617614c', max_length=64),
        ),
        migrations.AlterField(
            model_name='mail',
            name='text',
            field=models.TextField(),
        ),
    ]
