# Generated by Django 5.1.4 on 2024-12-27 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_mail_auth_alter_mail_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='auth',
            field=models.CharField(default='83bfd0595d49d44de22eabb366b786310f52f678a854e0bda8ef3aa18c156160', max_length=64, unique=True),
        ),
    ]
