# Generated by Django 5.1.4 on 2024-12-27 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_mail_auth_alter_mail_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mail',
            name='auth',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
